### PR TITLE
Review of jl and py notebooks

### PR DESCRIPTION
**Pull request by mmcky**
Review of `jl` and `py` notebook generation

- [x] review build script
- [x] review run script
- [ ] improve kernel support in jupytext generated notebooks
- [x] py noteboks running
- [x] jl notebooks running

I have added an environment file for the `python` side as these files **require** `python>=3.10`

### CODE REVIEW

**Comment by mmcky** [comment]
@jstac the file `s_approx.jl` is missing from the repo.

**Comment by jstac** [comment]
Thanks @mmcky , added.

**Comment by mmcky** [comment]
- [ ] update README with `python` version requirements and `Julia` version requirements

**Comment by jstac** [comment]
Thanks @mmcky !

**Pull request merged**
